#!/usr/bin/env bash
#####################################
#Une os comandos cat e less. É isso.#
############################################
#Join the commands cat and less. That's it.#
############################################
read -ep "File name: " file
cat $file | less
